// Code generated by "stringer -linecomment -type QueryType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Word-0]
	_ = x[Number-1]
}

const _QueryType_name = "wordnumber"

var _QueryType_index = [...]uint8{0, 4, 10}

func (i QueryType) String() string {
	if i < 0 || i >= QueryType(len(_QueryType_index)-1) {
		return "QueryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryType_name[_QueryType_index[i]:_QueryType_index[i+1]]
}
