repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.1
    hooks:
      - id: eslint
        files: '^src'
        types: []
        types_or: [javascript, vue]
        args:
          - --fix
