/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GitHubButton: typeof import('./src/components/GitHubButton.vue')['default']
    InteractiveConverter: typeof import('./src/components/InteractiveConverter.vue')['default']
    InteractiveResult: typeof import('./src/components/InteractiveResult.vue')['default']
    InteractiveToolbar: typeof import('./src/components/InteractiveToolbar.vue')['default']
    InteractiveWords: typeof import('./src/components/InteractiveWords.vue')['default']
    NumberConverter: typeof import('./src/components/NumberConverter.vue')['default']
    PageLayout: typeof import('./src/layouts/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulesTable: typeof import('./src/components/RulesTable.vue')['default']
    UpdateSnackbar: typeof import('./src/components/UpdateSnackbar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBottomNavigation: typeof import('vuetify/lib')['VBottomNavigation']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VMain: typeof import('vuetify/lib')['VMain']
    VRow: typeof import('vuetify/lib')['VRow']
    VSimpleTable: typeof import('vuetify/lib')['VSimpleTable']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsItems: typeof import('vuetify/lib')['VTabsItems']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
    WordConverter: typeof import('./src/components/WordConverter.vue')['default']
  }
}
